export const BEFORE_STATE = "BEFORE_STATE"

export const REVIEW_SUCCESS = "REVIEW_SUCCESS"
export const REVIEW_ERROR = "REVIEW_ERROR"

export const RE_CREATE_SUCCESS = "RE_CREATE_SUCCESS"
export const RE_CREATE_ERROR = "RE_CREATE_ERROR"