export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_ERROR = "LOGIN_ERROR"

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_ERROR = "LOGOUT_ERROR"

export const USER_SUCCESS = "USER_SUCCESS"
export const USER_ERROR = "USER_ERROR"

export const BEFORE_STATE = "BEFORE_STATEs"